### ISSUE TITLE
Error doing job: Task exception was never retrieved (None)

### ISSUE THREAD

**Issue by cofw2005** [JonasJoKuJonas/homeassistant-WebUntis#162]
### The problem

After upgrade to 1.3.0 I get two different errors for 221 times so far. Detailed error log see below.

Don't know if it is caused by these errors, all the sensors and binary_sensor were not updated any more since Monday morning.

### Version of Home Assistant?

2024.8.3

### What type of installation are you running?

Home Assistant OS

### Version of WebUntis

1.3.0

### Last working WebUntis version

1.2.5

### Traceback/Error logs

- First error:
Traceback (most recent call last):
  File "/config/custom_components/webuntis/__init__.py", line 264, in async_update
    await self._async_status_request()
  File "/config/custom_components/webuntis/__init__.py", line 496, in _async_status_request
    await self.update_notify()
  File "/config/custom_components/webuntis/__init__.py", line 1052, in update_notify
    changes = get_changes(change, lesson, lesson_old, server=self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webuntis/notify.py", line 228, in get_changes
    changes["subject"] = get_lesson_name(server=server, lesson=lesson)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webuntis/utils/web_untis.py", line 37, in get_lesson_name
    name = lesson.subjects[0].long_name
           ^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'subjects'

- Second Error:
{'jsonrpc': '2.0', 'id': '2024-10-15 21:03:48.314059', 'error': {'message': 'not authenticated', 'code': -8520}}
{'jsonrpc': '2.0', 'id': '2024-10-15 21:13:48.314852', 'error': {'message': 'not authenticated', 'code': -8520}}
{'jsonrpc': '2.0', 'id': '2024-10-15 21:23:48.317719', 'error': {'message': 'not authenticated', 'code': -8520}}
{'jsonrpc': '2.0', 'id': '2024-10-15 21:33:48.318059', 'error': {'message': 'not authenticated', 'code': -8520}}
{'jsonrpc': '2.0', 'id': '2024-10-15 21:43:48.320080', 'error': {'message': 'not authenticated', 'code': -8520}}

**Comment by JonasJoKuJonas** [comment]
fixed in v1.3.1
