### ISSUE TITLE
Can't load calendar in v2.0OSError(107, 'Socket not connected')

### ISSUE THREAD

**Issue by sevorl** [JonasJoKuJonas/homeassistant-WebUntis#29]
In v0.2.0-beta, I was able to load a calendar.
After updating to v0.20 (without beta), the calendar no longer loads. 
I get the following logs:

logger: custom_components.webuntis
Source: custom_components/webuntis/__init__.py:48
Integration: Web Untis ([documentation](https://github.com/JonasJoKuJonas/homeassistant-WebUntis/), [issues](https://github.com/JonasJoKuJonas/homeassistant-WebUntis/issues))
First occurred: 09:35:06 (1 occurrences)
Last logged: 09:35:06

Login to WebUntis 'schuleXXXXX@nameXXXXX' failed - OSError: ('Connection aborted.', OSError(107, 'Socket not connected'))

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/webuntis/calendar.py", line 28, in async_setup_entry
    entities = [UntisCalendar(server)]
  File "/config/custom_components/webuntis/calendar.py", line 47, in __init__
    self.events.sort(key=lambda e: (e.start, e.end))
AttributeError: 'NoneType' object has no attribute 'sort'

**Comment by sevorl** [comment]
It seems this was a temporary problem at the untis servers, not at the integration. It works now.
However, it might be good to handle this error somehow

**Comment by JonasJoKuJonas** [comment]
#30
